# Generated by Django 2.2 on 2020-06-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='message',
            field=models.TextField(blank=True, help_text='Message', null=True, verbose_name='Message'),
        ),
    ]
