# Generated by Django 2.2 on 2020-07-02 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0003_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='user',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='user',
            field=models.ManyToManyField(related_name='newsleter_user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
