# Generated by Django 2.2 on 2020-07-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_subscribeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscribeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancel')], default=0, verbose_name='Status')),
            ],
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='category',
            field=models.IntegerField(choices=[(0, 'All User'), (1, 'Registered User'), (2, 'Subscriber User'), (3, 'Specific User')], default=0, verbose_name='Type'),
        ),
    ]
