# Generated by Django 2.2 on 2020-12-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_auto_20200716_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Newsletter'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscribeuser',
            options={'verbose_name': 'NewsletterSubscribeUser'},
        ),
        migrations.AlterModelOptions(
            name='subscribeuser',
            options={'verbose_name': 'SubscribeUser'},
        ),
        migrations.AlterModelOptions(
            name='supportcategory',
            options={'verbose_name': 'SupportCategory'},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'verbose_name': 'SupportTicket'},
        ),
        migrations.AlterModelOptions(
            name='supportticketdetails',
            options={'verbose_name': 'SupportTicketDetails'},
        ),
        migrations.AlterModelTable(
            name='newsletter',
            table='DbNwYgfcQ4osKvrl',
        ),
        migrations.AlterModelTable(
            name='newslettersubscribeuser',
            table='0CiKyhb05gCOp4mB',
        ),
        migrations.AlterModelTable(
            name='subscribeuser',
            table='qdGChrivvbABICCF',
        ),
        migrations.AlterModelTable(
            name='supportcategory',
            table='Ww7tRv26SA7LAiQF',
        ),
        migrations.AlterModelTable(
            name='supportticket',
            table='TH3qkdA9J3URDVHw',
        ),
        migrations.AlterModelTable(
            name='supportticketdetails',
            table='MBA4H1rKHZhDfggS',
        ),
    ]
