# Generated by Django 2.2 on 2021-07-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_auto_20201229_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscribeuser',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
    ]
