# Generated by Django 2.2 on 2019-10-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_master', '0003_auto_20191005_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone Number')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject')),
                ('message', models.TextField(blank=True, help_text='Message', null=True, verbose_name='Message')),
                ('reply', models.TextField(blank=True, help_text='Message', null=True, verbose_name='Message')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancel')], default=0, verbose_name='Status')),
                ('read_status', models.IntegerField(choices=[(0, 'Unread'), (1, 'Read')], default=0, verbose_name='Read Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
