# Generated by Django 2.2 on 2019-10-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_master', '0004_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(default=1, help_text='Message', verbose_name='Message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactus',
            name='reply',
            field=models.TextField(blank=True, help_text='Message', null=True, verbose_name='Reply'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(default=1, max_length=50, verbose_name='Subject'),
            preserve_default=False,
        ),
    ]
