# Generated by Django 2.2 on 2019-10-07 13:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_master', '0007_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Content', verbose_name='Content'),
        ),
    ]
