# Generated by Django 2.2 on 2020-12-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_master', '0010_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cms_staticcontent',
            options={'verbose_name': 'Cms_StaticContent'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contactus'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name': 'EmailTemplate'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Faq'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Testimonial'},
        ),
        migrations.AlterModelTable(
            name='cms_staticcontent',
            table='ax7XI2mneaLpb7Ud',
        ),
        migrations.AlterModelTable(
            name='contactus',
            table='tg3bHbh1qpLYMIaS',
        ),
        migrations.AlterModelTable(
            name='emailtemplate',
            table='rfkF0iB1AluS2NNQ',
        ),
        migrations.AlterModelTable(
            name='faq',
            table='gAoTkpN4b2jBB6tV',
        ),
        migrations.AlterModelTable(
            name='testimonial',
            table='DC1MIHelrUsOiies',
        ),
    ]
