# Generated by Django 2.2 on 2021-04-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_master', '0011_auto_20201228_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('All user', 'All user'), ('Registered user', 'Registered user'), ('Subscribed user', 'Subscribed user')], default='', max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subj', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'TfFGdWoiaPvleABv',
            },
        ),
        migrations.CreateModel(
            name='Subscribeuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailaddress', models.CharField(max_length=50)),
                ('subscribe_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Z0EDN1feYgvqc7eB',
            },
        ),
    ]
