# Generated by Django 2.2 on 2020-12-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20191005_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menumodules',
            options={'verbose_name': 'MenuModules'},
        ),
        migrations.AlterModelTable(
            name='menumodules',
            table='8yHbadiSPqTR4E0L',
        ),
    ]
