# Generated by Django 2.2 on 2021-05-04 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('percentage', models.CharField(max_length=50, verbose_name='Percentage')),
                ('colour', models.CharField(blank=True, max_length=50, null=True, verbose_name='Colour')),
                ('content', models.TextField(blank=True, help_text='Content', null=True, verbose_name='Content')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancel')], default=0, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokeninformation_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokeninformation_modified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TokenInformation',
                'verbose_name_plural': 'TokenInformation',
                'db_table': 'kGR7rx1syW59TxKz',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TokenDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('symbol', models.CharField(max_length=50, verbose_name='Symbol')),
                ('platform', models.CharField(max_length=50, verbose_name='Platform')),
                ('supply', models.CharField(max_length=50, verbose_name='Total Supply')),
                ('content', models.TextField(blank=True, help_text='Content', null=True, verbose_name='Content')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancel')], default=0, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokendetails_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokendetails_modified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TokenDetails',
                'verbose_name_plural': 'TokenDetails',
                'db_table': 'dT55INJGxASL7ISW',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('years', models.CharField(max_length=50, verbose_name='Years')),
                ('content', models.TextField(blank=True, help_text='Content', null=True, verbose_name='Content')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancel')], default=0, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_modified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RoadMap',
                'verbose_name_plural': 'RoadMaps',
                'db_table': 'cPWZ2sKnkhxQPL4c',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('symbol', models.CharField(max_length=50, verbose_name='Symbol')),
                ('platform', models.CharField(max_length=50, verbose_name='Platform')),
                ('supply', models.CharField(max_length=50, verbose_name='Total Supply')),
                ('content', models.TextField(blank=True, help_text='Content', null=True, verbose_name='Content')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancel')], default=0, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencydetails_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencydetails_modified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CurrencyDetails',
                'verbose_name_plural': 'CurrencyDetails',
                'db_table': 'fVqNkSDHT1M6Z0D6',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='tokeninformation',
            index=models.Index(fields=['name', 'percentage', 'status'], name='kGR7rx1syW5_name_577d72_idx'),
        ),
        migrations.AddIndex(
            model_name='tokendetails',
            index=models.Index(fields=['name', 'symbol', 'status'], name='dT55INJGxAS_name_0e0d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['title', 'years', 'status'], name='cPWZ2sKnkhx_title_7a17c8_idx'),
        ),
        migrations.AddIndex(
            model_name='currencydetails',
            index=models.Index(fields=['name', 'symbol', 'status'], name='fVqNkSDHT1M_name_372728_idx'),
        ),
    ]
