# Generated by Django 2.2 on 2021-05-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptotoken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencydetails',
            name='attachments',
            field=models.ImageField(blank=True, null=True, upload_to='currencywhitepaper', verbose_name='WhitePaper'),
        ),
    ]
