# Generated by Django 2.2 on 2021-05-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptotoken', '0002_currencydetails_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencydetails',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='currencywhitepaper', verbose_name='WhitePaper'),
        ),
    ]
