# Generated by Django 2.2 on 2021-05-05 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cryptotoken', '0003_auto_20210504_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencydetails',
            name='timerdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
