# Generated by Django 2.2 on 2021-05-05 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cryptotoken', '0004_currencydetails_timerdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencydetails',
            name='timerdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date'),
        ),
    ]
