# Generated by Django 2.2 on 2021-05-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptotoken', '0005_auto_20210505_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendetails',
            name='liquidity_lock',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancel')], default=0, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='tokendetails',
            name='liquidtypool',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Liquidity Pool'),
        ),
        migrations.AddField(
            model_name='tokendetails',
            name='pancakeswap',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PancakeSwap Price'),
        ),
        migrations.AddField(
            model_name='tokendetails',
            name='presaleprice',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dx Sale Pre-Sale Price'),
        ),
        migrations.AddField(
            model_name='tokendetails',
            name='presupply',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pre-Sale Supply '),
        ),
        migrations.AddField(
            model_name='tokendetails',
            name='teamwallet',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Total Wallet'),
        ),
        migrations.AddField(
            model_name='tokendetails',
            name='token_burn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Token Burn'),
        ),
        migrations.AlterField(
            model_name='tokendetails',
            name='supply',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Total Supply'),
        ),
    ]
