# Generated by Django 2.2 on 2021-05-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptotoken', '0007_auto_20210510_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencydetails',
            name='charity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Charity Wallet (%)'),
        ),
        migrations.AlterField(
            model_name='currencydetails',
            name='marketing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Marketing Wallet (%)'),
        ),
        migrations.AlterField(
            model_name='currencydetails',
            name='reward_distributed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Distributor Holder (%)'),
        ),
        migrations.AlterField(
            model_name='currencydetails',
            name='teamwallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Team Wallet (%)'),
        ),
        migrations.AlterField(
            model_name='currencydetails',
            name='token_burn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Token Burn (%)'),
        ),
    ]
