# Generated by Django 2.2 on 2021-05-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptotoken', '0008_auto_20210510_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencydetails',
            name='liquidtypool',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Liquidity Pool (%) (PancakeSwap)'),
        ),
        migrations.AlterField(
            model_name='currencydetails',
            name='presupply',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Pre-Sale Supply (%) (DxSale)'),
        ),
    ]
