# Generated by Django 2.2 on 2021-05-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser_profile',
            name='emailaddress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Address'),
        ),
    ]
