# Generated by Django 2.2 on 2019-10-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_settings',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='company_settings',
            name='modified_on',
        ),
    ]
