# Generated by Django 2.2 on 2020-06-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20191001_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_settings',
            name='depositurl',
            field=models.CharField(blank=True, default='Deposit Video Url', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company_settings',
            name='withdrawurl',
            field=models.CharField(blank=True, default='Withdraw Video Url', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company_settings',
            name='free_bonus_status',
            field=models.IntegerField(choices=[(0, 'Live'), (1, 'Under Maintenance')], default=1, verbose_name='Bonus Provide Status'),
        ),
        migrations.AlterField(
            model_name='company_settings',
            name='new_coin_status',
            field=models.IntegerField(choices=[(0, 'Live'), (1, 'Under Maintenance')], default=1, verbose_name='Fees Status'),
        ),
        migrations.AlterField(
            model_name='company_settings',
            name='site_maintenance_status',
            field=models.IntegerField(choices=[(0, 'Live'), (1, 'Under Maintenance')], default=1, verbose_name='Site Maintenance'),
        ),
    ]
