# Generated by Django 2.2 on 2020-06-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200629_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_settings',
            name='depositurl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Deposit Video Url'),
        ),
        migrations.AlterField(
            model_name='company_settings',
            name='withdrawurl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Withdraw Video Url'),
        ),
    ]
