# Generated by Django 2.2 on 2020-12-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200629_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='gplus',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Youtube'),
        ),
    ]
