# Generated by Django 2.2 on 2020-12-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20201209_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_settings',
            name='adminipaddress',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Admin IP Address'),
        ),
    ]
