# Generated by Django 2.2 on 2020-12-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_settings_adminipaddress'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='Qy3Lp6BUavODzKxC',
        ),
        migrations.AlterModelTable(
            name='company_branches',
            table='SGSEeKuePkYIl06b',
        ),
        migrations.AlterModelTable(
            name='company_settings',
            table='tt1PHI2VMhaXFIlt',
        ),
    ]
