# Generated by Django 2.2 on 2021-04-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20201228_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_settings',
            name='depositurl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Token Explore Url'),
        ),
    ]
