# Generated by Django 2.2 on 2021-05-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20210429_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Reddit'),
        ),
        migrations.AlterField(
            model_name='company',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram'),
        ),
    ]
