# Generated by Django 2.2 on 2021-05-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20210518_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address1',
            field=models.CharField(max_length=200, verbose_name='Contact Address'),
        ),
    ]
