# Generated by Django 2.2 on 2021-05-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20210518_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_settings',
            name='coingecko',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CoinGecko Cap Url'),
        ),
        migrations.AddField(
            model_name='company_settings',
            name='coinmarket',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CoinMarket Cap Url'),
        ),
    ]
