# Generated by Django 2.2 on 2021-05-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20210527_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='social1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Reddit'),
        ),
        migrations.AddField(
            model_name='company',
            name='social2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Reddit'),
        ),
        migrations.AlterField(
            model_name='company',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='company',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='linkedin'),
        ),
    ]
