# Generated by Django 2.2 on 2021-05-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_company_social3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='social2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Discord'),
        ),
        migrations.AlterField(
            model_name='company',
            name='social3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='WeChat'),
        ),
    ]
