# Generated by Django 2.2 on 2021-06-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20210527_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Company', max_length=50, verbose_name='Site Name'),
        ),
    ]
