# Generated by Django 2.2 on 2021-06-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20210603_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_branches',
            name='name',
            field=models.CharField(default='Branch', max_length=50, verbose_name='Branch Name'),
        ),
    ]
