# Generated by Django 2.2 on 2021-06-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20210603_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_settings',
            name='new_coin_status',
            field=models.IntegerField(choices=[(0, 'Disable'), (1, 'Enable')], default=0, verbose_name='Comming Soon'),
        ),
    ]
