# Generated by Django 2.2 on 2021-06-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_auto_20210603_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_video',
            field=models.FileField(blank=True, null=True, upload_to='videofiles', verbose_name='Site Video'),
        ),
    ]
