# Generated by Django 2.2 on 2021-05-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useraddress', models.CharField(max_length=100, verbose_name='Address')),
                ('contractid', models.IntegerField(default=0, verbose_name='Contract ID')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancelled')], default=0, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Useraddress',
                'db_table': 'APLegJVs5IOqnDex',
            },
        ),
    ]
