# Generated by Django 2.2 on 2021-05-25 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
